services:
  - type: web
    name: collabglow-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health

